apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: i0eamzozb-python 
  janus-idp.io/tekton: i0eamzozb-python
  backstage.io/kubernetes-id: i0eamzozb-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: i0eamzozb-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml